{% set version = "1.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tsclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TSclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TSclust/TSclust_{{ version }}.tar.gz
  sha256: 506a7a352cf7c25bc014f5a4b01b8c8fc04a72cf0ccb52f2540bfce3344149de

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libxfixes  # [linux]
  host:
    - r-base
    - r-kernsmooth
    - r-cluster
    - r-dtw
    - r-forecast
    - r-locpol
    - r-longitudinaldata
    - r-pdc
  run:
    - r-base
    - r-kernsmooth
    - r-cluster
    - r-dtw
    - r-forecast
    - r-locpol
    - r-longitudinaldata
    - r-pdc

test:
  requires:
    - xorg-libxfixes  # [linux]
  commands:
    - LD_LIBRARY_PATH="${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib" $R -e "library('TSclust')"  # [not win]
    - "\"%R%\" -e \"library('TSclust')\""  # [win]

about:
  home: http://www.jstatsoft.org/v62/i01/
  license: GPL-2.0-only
  summary: A set of measures of dissimilarity between time series to perform time series clustering. Metrics based on raw data, on generating models and on the forecast behavior are implemented. Some additional utilities related to time series clustering are also provided, such as clustering algorithms and cluster evaluation
    metrics.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: TSclust
# Type: Package
# Title: Time Series Clustering Utilities
# Version: 1.2.4
# Date: 2017-10-15
# Encoding: UTF-8
# Author: Pablo Montero Manso, JosA Antonio Vilar
# Maintainer: Pablo Montero <pmontm@gmail.com>
# Description: A set of measures of dissimilarity between time series to perform time series clustering. Metrics based on raw data, on generating models and on the forecast behavior are implemented. Some additional utilities related to time series clustering are also provided, such as clustering algorithms and cluster evaluation metrics.
# License: GPL-2
# URL: http://www.jstatsoft.org/v62/i01/
# Depends: R (>= 3.0.1), wmtsa, pdc, cluster
# Imports: locpol, KernSmooth, dtw, longitudinalData
# NeedsCompilation: no
# Packaged: 2017-10-15 19:42:51 UTC; pmont
# Repository: CRAN
# Date/Publication: 2017-10-16 23:13:27 UTC
